# Generated by Django 2.1.4 on 2020-02-21 15:48

from djongo import models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lemmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('language', models.TextField()),
                ('definition', models.TextField(blank=True)),
                ('explanation', models.TextField(blank=True)),
                ('terms', models.ManyToManyField(to='lemmas.Lemma')),
            ],
        ),
        migrations.CreateModel(
            name='MultiLingualConcept',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('concepts',
                 models.ForeignKey(
                     on_delete=django.db.models.deletion.CASCADE,
                     to='terms.Concept')),
            ],
        ),
    ]
