# Generated by Django 2.1.4 on 2020-02-21 16:53

from djongo import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilingualconcept',
            name='name',
            field=models.TextField(default='uff'),
            preserve_default=False,
        ),
    ]
