# Generated by Django 2.1.4 on 2020-02-21 17:02

from djongo import models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_multilingualconcept_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilingualconcept',
            name='concepts',
        ),
        migrations.AddField(
            model_name='concept',
            name='mconcept',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to='terms.MultiLingualConcept'),
            preserve_default=False,
        ),
    ]
