# Generated by Django 2.1.4 on 2020-02-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0001_initial'),
        ('terms', '0003_auto_20200221_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='terms',
        ),
        migrations.AddField(
            model_name='multilingualconcept',
            name='terms',
            field=models.ManyToManyField(to='lemmas.Lemma'),
        ),
    ]
