# Generated by Django 2.1.4 on 2020-02-24 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0004_auto_20200224_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='mconcept',
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='terms.MultiLingualConcept'),
        ),
    ]
