# Generated by Django 2.1.4 on 2020-02-24 13:27

from djongo import models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0005_auto_20200224_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='mconcept',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='terms.MultiLingualConcept'),
        ),
    ]
