# Generated by Django 2.1.4 on 2020-02-27 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0006_auto_20200224_1327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilingualconcept',
            name='terms',
        ),
    ]
