# Generated by Django 2.1.4 on 2020-02-27 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0002_lemma_concept'),
        ('terms', '0007_remove_multilingualconcept_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='multilingualconcept',
            name='lemma',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lemmaconcepts', to='lemmas.Lemma'),
        ),
    ]
