# Generated by Django 2.1.4 on 2020-02-27 13:29

from djongo import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0002_lemma_concept'),
        ('terms', '0008_multilingualconcept_lemma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multilingualconcept',
            name='lemma',
        ),
        migrations.AddField(
            model_name='multilingualconcept',
            name='lemma',
            field=models.ManyToManyField(null=True, related_name='lemmaconcepts', to='lemmas.Lemma'),
        ),
    ]
