# Generated by Django 2.1.4 on 2020-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0010_auto_20200227_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualconcept',
            name='lemma',
            field=models.ManyToManyField(related_name='lemmaconcepts', to='lemmas.Lemma'),
        ),
    ]
