# Generated by Django 2.2.10 on 2020-03-23 14:09

from djongo import models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0011_auto_20200228_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multilingualconcept',
            name='name',
            field=models.TextField(),
        ),
    ]
