# Generated by Django 2.1.4 on 2020-02-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0005_auto_20200227_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lemma',
            name='concept',
            field=models.ManyToManyField(related_name='terms', to='terms.Concept'),
        ),
    ]
