# Generated by Django 2.2.10 on 2020-03-23 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0006_auto_20200228_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lemma',
            old_name='partOfSpeech',
            new_name='pos',
        ),
    ]
